import type { ToolDefinition } from "@hukukai/types";

/**
 * MVP araç kataloğu — Bölüm 4.1 (Zorunlu modüller) ve Bölüm 7.2
 * (Günlük dil eşleştirmeleri) esas alınarak hazırlanmıştır.
 *
 * ÖNEMLİ: Bu dosya statik seed verisidir; üretimde ToolDefinition
 * tablosu tek kaynak olur (Bölüm 27 — "ToolDefinition merkezi kaynak
 * olmalı"). Bu dosya yalnızca ilk migration/seed script'i tarafından
 * kullanılır.
 */
export const TOOL_CATALOG_SEED: ToolDefinition[] = [
  {
    id: "tool_execution_preview",
    slug: "infaz-on-hesabi",
    name: "İnfaz Ön Hesabı",
    shortDescription:
      "Müddetname veya mahkeme kararına göre tahliye ve koşullu salıverme tarihini tahmin eder.",
    categories: ["İnfaz"],
    audiences: ["Vatandaş", "Avukat"],
    keywords: [
      "infaz",
      "cezaevi",
      "kac yil yatar",
      "ne zaman cikar",
      "tahliye",
      "kosullu saliverme",
      "denetimli serbestlik",
      "muddetname",
    ],
    synonyms: ["hapis suresi", "ceza infaz kurumu"],
    icon: "gavel",
    route: "/tools/infaz-on-hesabi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 2, lawyer: 3, accountant: 40 },
  },
  {
    id: "tool_traffic_fine_objection_deadline",
    slug: "trafik-cezasi-itiraz-suresi",
    name: "Trafik Cezası İtiraz Süresi",
    shortDescription:
      "Trafik idari para cezasına itiraz için kalan süreyi hesaplar.",
    categories: ["Trafik Cezaları", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: [
      "trafik cezasi",
      "radar cezasi",
      "cezaya itiraz",
      "sulh ceza",
      "kac gun icinde",
      "son gun",
      "indirimli odeme",
    ],
    synonyms: ["idari para cezasi itirazi", "trafik idari para cezasi"],
    icon: "car",
    route: "/tools/trafik-cezasi-itiraz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 3, lawyer: 6, accountant: 20 },
  },
  {
    id: "tool_traffic_fine_discount_deadline",
    slug: "trafik-cezasi-indirimli-odeme-suresi",
    name: "Trafik Cezası İndirimli Ödeme Süresi",
    shortDescription: "İndirimli ödeme için son günü hesaplar.",
    categories: ["Trafik Cezaları", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat"],
    keywords: [
      "trafik cezasi",
      "indirimli odeme",
      "erken odeme",
      "yuzde 25 indirim",
      "son odeme gunu",
    ],
    synonyms: ["pesin odeme indirimi"],
    icon: "percent",
    route: "/tools/trafik-cezasi-indirimli-odeme-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 5, lawyer: 10, accountant: 25 },
  },
  {
    id: "tool_self_employment_receipt",
    slug: "serbest-meslek-makbuzu",
    name: "Serbest Meslek Makbuzu",
    shortDescription:
      "Serbest meslek makbuzu oluşturur; netten brüte / brütten nete hesaplama yapar.",
    categories: ["Vergi", "Belge Oluşturma"],
    audiences: ["Avukat", "Mali Müşavir", "Vatandaş"],
    keywords: [
      "makbuz",
      "smm",
      "stopaj",
      "kdv",
      "netten brute",
      "brutten nete",
    ],
    synonyms: ["serbest meslek makbuzu olustur", "avukat makbuzu"],
    icon: "receipt",
    route: "/tools/serbest-meslek-makbuzu",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 8, lawyer: 4, accountant: 2 },
  },
  {
    id: "tool_legal_interest",
    slug: "yasal-faiz",
    name: "Yasal Faiz Hesaplama",
    shortDescription: "Yasal faiz ve temerrüt faizi tutarını hesaplar.",
    categories: ["Faiz ve Borç"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: [
      "faiz",
      "yasal faiz",
      "temerrut faizi",
      "gecikme faizi",
      "faiz hesapla",
    ],
    synonyms: ["kanuni faiz"],
    icon: "percent-circle",
    route: "/tools/yasal-faiz",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 6, lawyer: 2, accountant: 5 },
  },
  {
    id: "tool_enforcement_debt",
    slug: "icra-borcu",
    name: "İcra Borcu ve Faiz",
    shortDescription:
      "İcra takibindeki borç, işlemiş faiz ve masrafları hesaplar.",
    categories: ["İcra", "Faiz ve Borç"],
    audiences: ["Vatandaş", "Avukat"],
    keywords: [
      "icra",
      "icra borcu",
      "odeme emri",
      "icra takibi",
      "icra faizi",
    ],
    synonyms: ["icra dosya borcu"],
    icon: "banknote",
    route: "/tools/icra-borcu",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 4, lawyer: 1, accountant: 15 },
  },
  {
    id: "tool_enforcement_objection_deadline",
    slug: "icra-itiraz-suresi",
    name: "İcra İtiraz Süresi",
    shortDescription: "İlamsız takipte ödeme emrine itiraz süresini hesaplar.",
    categories: ["İcra", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat"],
    keywords: [
      "icra tebligati",
      "odeme emri",
      "itiraz suresi",
      "icraya itiraz",
      "kac gunum var",
    ],
    synonyms: ["icra odeme emrine itiraz"],
    icon: "calendar-clock",
    route: "/tools/icra-itiraz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 1, lawyer: 2, accountant: 30 },
  },
  {
    id: "tool_rent_increase",
    slug: "kira-artisi",
    name: "Kira Artışı Hesaplama",
    shortDescription: "Kira artış oranı ve yeni kira bedelini hesaplar.",
    categories: ["Kira"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: ["kira artisi", "kira zammi", "yeni kira bedeli", "tufe"],
    synonyms: ["kira zam orani"],
    icon: "home",
    route: "/tools/kira-artisi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 2, lawyer: 8, accountant: 12 },
  },
  {
    id: "tool_attorney_fee",
    slug: "vekalet-ucreti",
    name: "Vekâlet Ücreti Hesaplama",
    shortDescription: "Karşı taraf vekâlet ücretini tarifeye göre hesaplar.",
    categories: ["Vekâlet ve Harç"],
    audiences: ["Avukat"],
    keywords: ["vekalet ucreti", "avukatlik ucreti", "karsi taraf vekalet"],
    synonyms: ["avukatlik asgari ucret tarifesi"],
    icon: "scale",
    route: "/tools/vekalet-ucreti",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 30, lawyer: 3, accountant: 35 },
  },
  {
    id: "tool_court_fee",
    slug: "harc-on-hesabi",
    name: "Harç Ön Hesabı",
    shortDescription: "Dava ve icra harçlarını ön hesap olarak hesaplar.",
    categories: ["Vekâlet ve Harç"],
    audiences: ["Avukat", "Mali Müşavir"],
    keywords: ["harc", "dava harci", "icra harci", "harc hesapla"],
    synonyms: ["mahkeme harci"],
    icon: "coins",
    route: "/tools/harc-on-hesabi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 25, lawyer: 5, accountant: 20 },
  },
  {
    id: "tool_vat",
    slug: "kdv-hesapla",
    name: "KDV Hesaplama",
    shortDescription: "KDV dahil/hariç tutarları hesaplar.",
    categories: ["Vergi"],
    audiences: ["Mali Müşavir", "Avukat", "Vatandaş"],
    keywords: ["kdv", "kdv hesapla", "kdv dahil", "kdv haric"],
    synonyms: ["katma deger vergisi"],
    icon: "calculator",
    route: "/tools/kdv-hesapla",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 20, lawyer: 20, accountant: 1 },
  },
  {
    id: "tool_income_tax",
    slug: "gelir-vergisi",
    name: "Basit Gelir Vergisi Hesaplama",
    shortDescription: "Gelir vergisi dilimlerine göre ön hesap yapar.",
    categories: ["Vergi"],
    audiences: ["Mali Müşavir", "Vatandaş"],
    keywords: ["gelir vergisi", "vergi dilimi", "stopaj hesapla"],
    synonyms: ["gv hesapla"],
    icon: "calculator",
    route: "/tools/gelir-vergisi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 22, lawyer: 25, accountant: 2 },
  },
  {
    id: "tool_sgk_employer_cost",
    slug: "sgk-isveren-maliyeti",
    name: "Temel SGK İşveren Maliyeti",
    shortDescription: "Brüt maaş üzerinden işveren SGK maliyetini hesaplar.",
    categories: ["SGK"],
    audiences: ["Mali Müşavir"],
    keywords: ["sgk", "isveren maliyeti", "sgk primi", "bordro"],
    synonyms: ["sigorta primi hesapla"],
    icon: "briefcase",
    route: "/tools/sgk-isveren-maliyeti",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 40, lawyer: 40, accountant: 3 },
  },
  {
    id: "tool_document_analysis",
    slug: "belge-analiz-et",
    name: "Belge Analiz Et",
    shortDescription:
      "Yüklenen resmi belgeyi okur, türünü belirler ve ilgili araçları önerir.",
    categories: ["Belge Analizi"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: [
      "belge yukle",
      "belgeyi acikla",
      "tebligat geldi",
      "bu belge ne",
      "belge analizi",
    ],
    synonyms: ["dokuman analizi", "tebligat analizi"],
    icon: "file-search",
    route: "/tools/belge-analiz-et",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 1, lawyer: 1, accountant: 1 },
  },
  {
    id: "tool_enforcement_third_party_notice_objection_deadline",
    slug: "haciz-ihbarnamesi-itiraz-suresi",
    name: "Haciz İhbarnamesine İtiraz Süresi",
    shortDescription:
      "Üçüncü şahıs haciz ihbarnamesine itiraz için kalan süreyi hesaplar.",
    categories: ["İcra", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat"],
    keywords: [
      "haciz ihbarnamesi",
      "ucuncu sahis",
      "icra ihbarnamesi",
      "ihbarnameye itiraz",
    ],
    synonyms: ["icra ihbarnamesine itiraz"],
    icon: "calendar-clock",
    route: "/tools/haciz-ihbarnamesi-itiraz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 7, lawyer: 4, accountant: 32 },
  },
  {
    id: "tool_tax_court_action_deadline",
    slug: "vergi-mahkemesi-dava-suresi",
    name: "Vergi Mahkemesi Dava Açma Süresi",
    shortDescription:
      "Vergi/ceza ihbarnamesine karşı vergi mahkemesinde dava açma süresini hesaplar.",
    categories: ["Vergi", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: [
      "vergi ihbarnamesi",
      "vergi mahkemesi",
      "vergi dava suresi",
      "dava acma suresi",
    ],
    synonyms: ["vergi davasi suresi"],
    icon: "calendar-clock",
    route: "/tools/vergi-mahkemesi-dava-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 18, lawyer: 9, accountant: 6 },
  },
  {
    id: "tool_tax_settlement_application_deadline",
    slug: "vergi-uzlasma-basvuru-suresi",
    name: "Vergi Uzlaşma Başvuru Süresi",
    shortDescription:
      "Dava açmadan önce vergi idaresiyle uzlaşma başvurusu için son günü hesaplar.",
    categories: ["Vergi", "Mahkeme Süreleri"],
    audiences: ["Vatandaş", "Avukat", "Mali Müşavir"],
    keywords: ["vergi uzlasma", "uzlasma basvurusu", "vergi ihbarnamesi"],
    synonyms: ["vergi uzlasma suresi"],
    icon: "calendar-clock",
    route: "/tools/vergi-uzlasma-basvuru-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 19, lawyer: 11, accountant: 7 },
  },
  {
    id: "tool_sgk_objection_deadline",
    slug: "sgk-itiraz-suresi",
    name: "SGK İtiraz Süresi",
    shortDescription:
      "SGK idari para cezası/işlemine itiraz için kalan süreyi hesaplar.",
    categories: ["SGK", "Mahkeme Süreleri"],
    audiences: ["Mali Müşavir", "Avukat", "Vatandaş"],
    keywords: ["sgk itirazi", "sgk idari para cezasi", "sgk tebligati"],
    synonyms: ["sgk itiraz suresi"],
    icon: "briefcase",
    route: "/tools/sgk-itiraz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 42, lawyer: 42, accountant: 4 },
  },
  {
    id: "tool_court_appeal_deadline",
    slug: "istinaf-suresi",
    name: "İstinaf Süresi",
    shortDescription:
      "Hukuk yargılamasında gerekçeli karara karşı istinaf başvuru süresini hesaplar " +
      "(yalnızca hukuk davaları — ceza yargılaması için 'Ceza Yargılamasında " +
      "İstinaf Süresi' aracını kullanın).",
    categories: ["Mahkeme Süreleri"],
    audiences: ["Avukat", "Vatandaş"],
    keywords: ["istinaf", "istinaf suresi", "gerekceli karar", "bam"],
    synonyms: ["bölge adliye mahkemesi süresi"],
    icon: "gavel",
    route: "/tools/istinaf-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 15, lawyer: 7, accountant: 45 },
  },
  {
    id: "tool_court_cassation_deadline",
    slug: "temyiz-suresi",
    name: "Temyiz Süresi",
    shortDescription:
      "Hukuk yargılamasında bölge adliye mahkemesi kararına karşı temyiz süresini " +
      "hesaplar (yalnızca hukuk davaları — ceza yargılaması için 'Ceza " +
      "Yargılamasında Temyiz Süresi' aracını kullanın).",
    categories: ["Mahkeme Süreleri"],
    audiences: ["Avukat", "Vatandaş"],
    keywords: ["temyiz", "yargitay", "temyiz suresi"],
    synonyms: ["yargıtay başvuru süresi"],
    icon: "gavel",
    route: "/tools/temyiz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 16, lawyer: 8, accountant: 46 },
  },
  {
    id: "tool_criminal_court_appeal_deadline",
    slug: "ceza-istinaf-suresi",
    name: "Ceza Yargılamasında İstinaf Süresi",
    shortDescription:
      "Ceza yargılamasında gerekçeli hükme karşı istinaf başvuru süresini hesaplar. " +
      "1 Haziran 2024'ten önce/sonra verilen kararlar için farklı kurallar otomatik " +
      "uygulanır (7499 sayılı Kanun).",
    categories: ["Mahkeme Süreleri"],
    audiences: ["Avukat", "Vatandaş"],
    keywords: [
      "ceza istinaf",
      "istinaf suresi ceza",
      "hukmun aciklanmasi",
      "bam ceza dairesi",
    ],
    synonyms: ["ceza dairesi istinaf süresi"],
    icon: "gavel",
    route: "/tools/ceza-istinaf-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 17, lawyer: 6, accountant: 47 },
  },
  {
    id: "tool_criminal_court_cassation_deadline",
    slug: "ceza-temyiz-suresi",
    name: "Ceza Yargılamasında Temyiz Süresi",
    shortDescription:
      "Ceza yargılamasında bölge adliye mahkemesi kararına karşı temyiz süresini " +
      "hesaplar. 1 Haziran 2024'ten önce/sonra verilen kararlar için farklı " +
      "kurallar otomatik uygulanır (7499 sayılı Kanun).",
    categories: ["Mahkeme Süreleri"],
    audiences: ["Avukat", "Vatandaş"],
    keywords: ["ceza temyiz", "yargitay ceza dairesi", "temyiz suresi ceza"],
    synonyms: ["ceza dairesi temyiz süresi"],
    icon: "gavel",
    route: "/tools/ceza-temyiz-suresi",
    isActive: true,
    isBeta: false,
    requiresSubscription: false,
    sortPriorityByRole: { citizen: 18, lawyer: 7, accountant: 48 },
  },
];
